[do really bad thing to avoid compiler error, intr. in dash#5206]
breaks tests, naturally

Errors
------------------------------
In file included from rpc/quorums.cpp:14:
./evo/deterministicmns.h: In lambda function:
./evo/deterministicmns.h:238:85: error: 'this' was not captured for this lambda function
         return ranges::count_if(mnMap, [](const auto& p){ return IsMNValid(*p.second); });
                                                                                     ^
./evo/deterministicmns.h: In lambda function:
./evo/deterministicmns.h:248:132: error: 'this' was not captured for this lambda function
         return ranges::count_if(mnMap, [](const auto& p) { return p.second->nType == MnType::HighPerformance && IsMNValid(*p.second); });
                                                                                                                                    ^
./evo/deterministicmns.h: In lambda function:
./evo/deterministicmns.h:254:89: error: 'this' was not captured for this lambda function
                                                                 if (!IsMNValid(*p.second)) return res;
                                                                                         ^